// 把 dsh 插件打包为单文件 ESM：dsh-plugin/index.mjs（仓库根 dsh 组合包 dida-todo 的入口）。
// 运行时依赖只有 @suibiji/dida-cli（子进程调用），由 createRequire 从插件所在目录解析。
import { build } from "esbuild";

await build({
  entryPoints: ["extensions/dsh/index.ts"],
  outfile: "dsh-plugin/index.mjs",
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  external: ["@suibiji/dida-cli"],
  banner: { js: "// dida-todo dsh plugin — generated by scripts/build-dsh.mjs, do not edit." },
  logLevel: "warning",
});
console.log("built dsh-plugin/index.mjs");
